/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kerem.mvnveritabani;

import com.kerem.mvnveritabani.datalar.KullaniciData;
import com.kerem.mvnveritabani.datalar.PersonelData;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import kisiler.Personel;

/**
 *
 * @author MKA
 */
public class frmTablo extends javax.swing.JFrame {

    PersonelData personeldat = new PersonelData();
    KullaniciData kullanicidata = new KullaniciData();
    Personel p = null;

    /**
     * Creates new form frmTablo
     */
    public frmTablo(Object o, int a) {
        initComponents();

        if (a == 1) {
        } else if (a == 2) {
            ptabloDoldur();
            this.p = (Personel) o;

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTablo = new javax.swing.JTable();
        btnEkle = new javax.swing.JButton();
        btnSil = new javax.swing.JButton();
        btnDegistir = new javax.swing.JButton();
        btnExcel = new javax.swing.JButton();
        btnDosya = new javax.swing.JButton();
        btnIncele = new javax.swing.JButton();
        btnIptal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTablo);

        btnEkle.setText("Ekle");
        btnEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEkleActionPerformed(evt);
            }
        });

        btnSil.setText("Sil");

        btnDegistir.setText("Değiştir");

        btnExcel.setText("Excele Aktar");

        btnDosya.setText("Dosyaya Aktar");
        btnDosya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosyaActionPerformed(evt);
            }
        });

        btnIncele.setText("İncele");

        btnIptal.setText("İptal");
        btnIptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIptalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEkle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(btnSil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDegistir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDosya, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIncele, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIptal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnEkle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDegistir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDosya)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIncele)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(btnIptal))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDosyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosyaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDosyaActionPerformed

    private void btnIptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIptalActionPerformed
        this.hide();       // TODO add your handling code here:
    }//GEN-LAST:event_btnIptalActionPerformed

    private void btnEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEkleActionPerformed
        dlgPersEkle dlgp = new dlgPersEkle(this, true);
        dlgp.show();
        ptabloDoldur();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEkleActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDegistir;
    private javax.swing.JButton btnDosya;
    private javax.swing.JButton btnEkle;
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnIncele;
    private javax.swing.JButton btnIptal;
    private javax.swing.JButton btnSil;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTablo;
    // End of variables declaration//GEN-END:variables

    public void ptabloDoldur() {
        List<Personel> pliste = personeldat.getAll();
        String[] headers = new String[]{"İD", "AD", "SOYAD", "SİCİL NO", "ADRES", "İŞ YERİ", "DOĞUM TARİHİ", "Cep Telefonu", "E-POSTA", "Notlar", "ŞEHİR", "İLÇE"};

        String[][] data = new String[pliste.size()][12];

        for (int a = 0; a < pliste.size(); a++) {
            data[a][0] = pliste.get(a).getId().toString();
            data[a][1] = pliste.get(a).getAd();
            data[a][2] = pliste.get(a).getSoyad();
            data[a][3] = String.valueOf(pliste.get(a).getSicilNo());
            data[a][4] = pliste.get(a).getAdres();
            data[a][7] = pliste.get(a).getIsyeri();
            if(pliste.get(a).getDogumTarihi()!=null)
                data[a][6] = pliste.get(a).getDogumTarihi().toLocaleString();
            data[a][5] = String.valueOf(pliste.get(a).getTelefonCep());
            data[a][8] = pliste.get(a).getEposta();
            data[a][9] = pliste.get(a).getNot();
            data[a][10] = pliste.get(a).getIl();
            data[a][11] = pliste.get(a).getIlce();

        }
        tblTablo.setModel(new DefaultTableModel(data, headers));
    }
}
